---
name: Build images

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - master

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    name: Setup Matrix
    outputs:
      puppet_unit_test_matrix: ${{ steps.get-outputs.outputs.puppet_unit_test_matrix }}
      puppet_beaker_test_matrix: ${{ steps.get-outputs.outputs.puppet_beaker_test_matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Setup Test Matrix
        id: get-outputs
        run: bundle exec metadata2gha

  beaker:
    needs: setup_matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      BEAKER_HYPERVISOR: podman
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.puppet_beaker_test_matrix)}}
    name: "${{ matrix.name }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: ${{ inputs.cache-version }}
          working-directory: ${{ inputs.working-directory }}
      - name: Run beaker
        run: bundle exec beaker-docker containerfile ${{ matrix.env.BEAKER_SETFILE }}
        env: ${{ matrix.env }}

  tests:
    if: always()
    needs:
      - setup_matrix
      - beaker
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
